# Generated by Django 3.2.6 on 2022-02-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='github',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('githubuser', models.CharField(max_length=1000)),
                ('imagelink', models.CharField(max_length=10000)),
                ('username', models.CharField(max_length=1000)),
            ],
        ),
    ]
